create table countries(country_code char(2) primary key, county_name text unique);
insert into countries(country_code, country_name) values ('us', 'United States');
insert into countries(country_code, country_name) values ('mx', 'Mexico');
insert into countries(country_code, country_name) values ('au', 'Australia');
insert into countries(country_code, country_name) values ('gb', 'United Kingdom);
insert into countries(country_code, country_name) values ('de', 'Germany');
create table cities(name text not null, postal_code varchar(9) check (postal_code <> ''), country_code char(2) references countries, primary key (country_code, postal_code));
insert into cities values ('Portland', '97205', 'us');
insert into cities values ('Munich', '80689', 'de');
insert into cities values ('Munich', '80686', 'de');
create table venues(venue_id serial primary key, name varchar(255), street_address text, type char(7) check(type in ('public','private')) default 'public', postal_code varchar(9), country_code char(2), foreign key (country_code, postal_code) Refererces cities(country_code,postal_code) match full);
insert into venues(name,postal_code,country_code) values ('Crystal Ballroom','97205','us');
insert into venues(name,postal_code,country_code) values ('Voodoo Donuts','97205','us');
create table events(title text, starts timestamp, ends timestamp, venue_id integer references venues, event_id serial primary key);
insert into events (title, starts, ends, venue_id) values ('LARP Club', '2012-02-15 17:30:00', '2012-02-15 19:30:00', 2);
insert into events (title, starts, ends) values ('April Fools Day', '2012-04-01 00:00:00', '2012-04-01 23:59:00');
insert into events (title, starts, ends) values ('Christmas', '2012-12-25 00:00:00', '2012-12-25 23:59:00');
select relname from pg_class where relnamespace='2200' and relkind='r';
select c.country_name from countries c right join (select v.country_code from venues v left join events e on v.venue_id=e.venue_id where e.title='LARP Club') as v on v.country_code=c.country_code;